PokemonFetching/PokemonFetching/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PokemonFetching.Models;
using System.Diagnostics.Metrics;
using System.Text;
using static System.Net.Mime.MediaTypeNames;

namespace PokemonFetching.Controllers
{
    public class LoginController : Controller
    {
        public static User user = new User();
        private readonly IConfiguration _configuration;
        public string api;

        public LoginController(IConfiguration configuration)
        {
            _configuration = configuration;
            api = _configuration.GetValue<string>("API");
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserDto request)
        {
            Console.WriteLine(api);
            Registration receivedReservation = new Registration();
            using (var httpClient = new HttpClient())
            {
                var content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync(api + "/Auth/login", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    if(response.ReasonPhrase == "OK")
                    {
                        return Redirect("/Home");
                    }
                }
            }
            return Redirect("/Login");
        }
    }
}

PokemonFetching/PokemonFetching/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PokemonFetching.Models;
using System.Text;

namespace PokemonFetching.Controllers
{
    public class RegisterController : Controller
    {
        private readonly IConfiguration _configuration;
        public string api;

        public RegisterController(IConfiguration configuration)
        {
            _configuration = configuration;
            api = _configuration.GetValue<string>("API");
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserDto request)
        {
            Registration receivedReservation = new Registration();
            using (var httpClient = new HttpClient())
            {
                var content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync(api + "/Auth/register", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    if (response.ReasonPhrase == "OK")
                    {
                        return Redirect("/Login");
                    }
                }
            }
            return Redirect("/Register");
        }
    }
}

PokemonFetching/PokemonFetching/Views/Login/Index.cshtml
@model UserDto
<html>
<head>

    <link rel="stylesheet" href="~/css/style.css" />
</head>

<body>
    <div class="login">
        <h1>Login to Web App</h1>

        <form method="post" asp-controller="Login" asp-action="Login">
            <p><input type="text" name="Username" value="" placeholder="Username.." required></p>
            <p><input type="password" name="Password" value="" placeholder="Password.." required></p>
            <p class="remember_me">
                <label>
                    <input type="checkbox" name="remember_me" id="remember_me">
                    Remember me on this computer
                </label>
            </p>
            <input style="margin-top: 10px; width: 85%;" class="btnLogin" type="submit" name="commit" value="Login">
            <a style="margin-top: 10px; width: 100%;" asp-controller="Register" asp-action="Index" class="btn btn-sm btn-secondary">Register</a>
                <hr />
        </form>
    </div>
    <script>
        $(document).ready(function () {
            $('header').empty();
            $('footer').empty();
        });
    </script>
</body>
</html>