PokemonFetching/PokemonFetching/Controllers/AccessController.cs
using Microsoft.AspNetCore.Mvc;

using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using PokemonFetching.Models;
using Newtonsoft.Json;
using System.Text;
using System.Windows;

namespace PokemonFetching.Controllers
{
    public class AccessController : Controller
    {
        private readonly IConfiguration _configuration;
        public string api;

        public AccessController(IConfiguration configuration)
        {
            _configuration = configuration;
            api = _configuration.GetValue<string>("API");
        }   
        public IActionResult Login()
        {
            ClaimsPrincipal claimUser = HttpContext.User;
            if (claimUser.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(VMLogin modelLogin)
        {
            if (ModelState.IsValid)
            {
                using (var httpClient = new HttpClient())
                {
                    
                    var content = new StringContent(JsonConvert.SerializeObject(modelLogin), Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync(api + "/Registration/login", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();

                        if (response.ReasonPhrase == "OK")
                        {
                            List<Claim> claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.NameIdentifier, modelLogin.Email),
                        new Claim(ClaimTypes.Name, modelLogin.Email),
                        new Claim("OtherProperties","Example Role")
                    };

                            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims,
                                CookieAuthenticationDefaults.AuthenticationScheme);

                            AuthenticationProperties properties = new AuthenticationProperties()
                            {
                                AllowRefresh = true,
                                IsPersistent = modelLogin.KeepLoggedIn
                            };

                            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                                new ClaimsPrincipal(claimsIdentity), properties);

                            var cookieOptions = new CookieOptions();
                            cookieOptions.Expires = DateTime.Now.AddDays(1);
                            cookieOptions.Path = "/";
                            Response.Cookies.Append("Email", modelLogin.Email, cookieOptions);



                            return RedirectToAction("Index", "Home");
                        }
                    }
                }
            ViewData["ValidateMessage"] = "User Not Found";
            }
            return View();
        }




        public IActionResult Register()
        {
            ClaimsPrincipal claimUser = HttpContext.User;
            if (claimUser.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(Registration modelLogin)
        {
            if (ModelState.IsValid)
            {
                Registration receiveLogin = new Registration();
                using (var httpClient = new HttpClient())
                {
                    var content = new StringContent(JsonConvert.SerializeObject(modelLogin), Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync(api + "/Registration/registration", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        if (response.ReasonPhrase == "OK")
                        {
                            List<Claim> claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.NameIdentifier, modelLogin.Email),
                        new Claim("OtherProperties","Example Role")
                    };

                            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims,
                                CookieAuthenticationDefaults.AuthenticationScheme);

                            AuthenticationProperties properties = new AuthenticationProperties()
                            {
                                AllowRefresh = true,
                                IsPersistent = modelLogin.KeepLoggedIn
                            };

                            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                                new ClaimsPrincipal(claimsIdentity), properties);

                            return RedirectToAction("Index", "Home");
                        }
                    }
                }
            }
            return View();
        }
    }
}

PokemonFetching/PokemonFetching/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PokemonFetching.Models;
using System.Diagnostics.Metrics;
using System.Text;
using static System.Net.Mime.MediaTypeNames;

namespace PokemonFetching.Controllers
{
    public class LoginController : Controller
    {
        public static User user = new User();
        private readonly IConfiguration _configuration;
        public string api;

        public LoginController(IConfiguration configuration)
        {
            _configuration = configuration;
            api = _configuration.GetValue<string>("API");
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserDto request)
        {
            Console.WriteLine(api);
            Registration receivedReservation = new Registration();
            using (var httpClient = new HttpClient())
            {
                var content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync(api + "/Auth/login", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    if(response.ReasonPhrase == "OK")
                    {
                        return Redirect("/Home");
                    }
                }
            }
            return Redirect("/Login");
        }
    }
}

PokemonFetching/PokemonFetching/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PokemonFetching.Models;
using System.Text;

namespace PokemonFetching.Controllers
{
    public class RegisterController : Controller
    {
        private readonly IConfiguration _configuration;
        public string api;

        public RegisterController(IConfiguration configuration)
        {
            _configuration = configuration;
            api = _configuration.GetValue<string>("API");
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserDto request)
        {
            Registration receivedReservation = new Registration();
            using (var httpClient = new HttpClient())
            {
                var content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync(api + "/Auth/register", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    if (response.ReasonPhrase == "OK")
                    {
                        return Redirect("/Login");
                    }
                }
            }
            return Redirect("/Register");
        }
    }
}

PokemonFetching/PokemonFetching/Views/Access/Login.cshtml
@model PokemonFetching.Models.VMLogin;

<html>
<head>

    <link rel="stylesheet" href="~/css/style.css" />
</head>

<body style="background-color: #171717;">
    <div class="login" style="box-shadow: 3px 5px 40px 3px rgba(255,255,255,0.75);
-webkit-box-shadow: 3px 5px 40px 3px rgba(255,255,255,0.75);
-moz-box-shadow: 3px 5px 40px 3px rgba(255,255,255,0.75); border-radius: 10px;">
        <h1 style="border-top-left-radius: 10px; border-top-right-radius: 10px;">Login</h1>

        <form method="post" asp-controller="Access" asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <p>
                <input type="text" name="Email" asp-for="Email" value="" placeholder="Email..." >
                <span asp-validation-for="Email" class="text-danger" style="color: red;"></span>
                </p>
            <p>
                <input type="password" name="Password" asp-for="Password" value="" placeholder="Password..." >
                <span asp-validation-for="Password" class="text-danger" style="color: red;"></span>
                </p>
            <p class="remember_me">
                <label>
                    <input type="checkbox" name="KeepLoggedIn" asp-for="KeepLoggedIn" id="remember_me">
                    Keep me Logged In
                </label>
            </p>
            <br />
            <br />
            <br />
            You don't have account? <a style="margin-top: 10px; width: 100%; font-size: 12px;" asp-controller="Access" asp-action="Register" class="btn btn-sm btn-secondary">Register now</a>
            <input style="margin-top: 10px; margin-bottom: 5px; width: 85%;" class="btnLogin" type="submit" name="commit" value="Login">
                <hr />
            @if (ViewData["ValidateMessage"] != null)
            {
                    <br />
                <label style="color: #ff3333; text-align: center; width: 100%; font-size: 15px; font-weight: 700;">@ViewData["ValidateMessage"]</label>
                }
        </form>
    </div>
</body>
</html>

@{
    Layout = null;
}

PokemonFetching/PokemonFetching/Views/Access/Register.cshtml
@model PokemonFetching.Models.Registration;
<html>
<head>

    <link rel="stylesheet" href="~/css/style.css" />
</head>

<body>
    <div class="login">
        <h1>Register</h1>

        <form method="post" asp-controller="Access" asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <p>
                <input type="text" name="UserName" asp-for="UserName" value="" placeholder="Username...">
                <span asp-validation-for="UserName" class="text-danger" style="color: red;"></span>
                </p>
            <p>
                <input type="text" name="Email" asp-for="Email" value="" placeholder="Email...">
                <span asp-validation-for="Email" class="text-danger" style="color: red;"></span>
            </p>
            <p>
                <input type="password" name="Password" asp-for="Password" value="" placeholder="Password...">
                <span asp-validation-for="Password" class="text-danger" style="color: red;"></span>
            </p>
            You have a account? <a style="margin-top: 10px; width: 100%; font-size: 12px;" asp-controller="Access" asp-action="Login" class="btn btn-sm btn-secondary">Back to login</a>
            <input style="margin-top: 20px; margin-bottom: 5px; width: 85%;" class="btnLogin" type="submit" name="commit" value="Register">
            <hr />
        </form>
    </div>
</body>
</html>

@{
    Layout = null;
}